services:
  web:
    build: ./backend
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend/src:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db:5432/leap_unpad"
      POSTGRES_DB: "leap_unpad"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: "leap"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres_data:
